apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
  labels:
    app: next-js
spec:
  replicas: 1
  selector:
    macthLabels:
      app: next-js
  template:
    metadata:
      labels:
        app: next-js
    spec:
      container:
      - name: next-js
        image: jingnin/next-image
        ports:
          - containerPort: 3000
        
