apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
  labels:
    app: next-js
spec:
  replicas: 1
  selector:
    matchLabels:  # Corrected from "macthLabels"
      app: next-js
  template:
    metadata:
      labels:
        app: next-js
    spec:
      containers:  # Corrected indentation for "containers"
      - name: next-js
        image: jingnin/next-img:17
        ports:
          - containerPort: 3000
